baseURL = "https://amplify-workshop.go-aws.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Amplify / AI Services / Workshop"
theme = "learn"
uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
#pygmentsCodeFencesGuessSyntax = true
#pygmentsStyle = "monokai"


[blackfriday]
hrefTargetBlank = true

[markup.goldmark.renderer]
unsafe = true # Optional, allows HTML inside your CommonMark content


[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Sathish Hariharab"
description = "Amplify / AI Services / Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true



[[menu.shortcuts]]


[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]
